presentation :-
  write(' ______________________________________________________'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|                  CONSTA BOARD GAME                   |'), nl,
  write('|                                                      |'), nl,
  write('|                        PLOG                          |'), nl,
  write('|                                                      |'), nl,
  write('|                        FEUP                          |'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|                1 - Human versus Human                |'), nl,
  write('|                                                      |'), nl,
  write('|             2 - Computer versus Computer             |'), nl,
  write('|                                                      |'), nl,
  write('|               3 - Human versus Computer              |'), nl,
  write('|                                                      |'), nl,
  write('|              4 - Set Computer Dificulty              |'), nl,
  write('|                                                      |'), nl,
  write('|                       5 - Exit                       |'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|               Eduardo Ramos 201505779                |'), nl,
  write('|               Xavier Fontes 201503145                |'), nl,
  write('|                                                      |'), nl,
  write('|                                                      |'), nl,
  write('|        Press the number to chose your battle!        |'), nl,
  write('|______________________________________________________|'), nl.
